# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='myuser',
            name='nick_name',
            field=models.CharField(default='True', max_length=20),
        ),
    ]
