# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 06:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title Of Post')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content Of Post')),
                ('tag', models.CharField(max_length=10)),
                ('writedDate', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=30)),
                ('boardTag', models.CharField(max_length=10)),
                ('alteredDate', models.DateTimeField(auto_now=True)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('dateTime_auto_now', models.DateTimeField(auto_now=True)),
                ('dateTime_auto_now_add', models.DateTimeField(auto_now_add=True)),
                ('helloWorld', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestModel22',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('dateTime_auto_now', models.DateTimeField(auto_now=True)),
                ('dateTime_auto_now_add', models.DateTimeField(auto_now_add=True)),
                ('helloWorld', models.DateTimeField()),
            ],
        ),
    ]
